### PR TITLE
[PLG-1312] Add stack identifier to `bitrise.yml` for `linux-build` workflow

### PR DESCRIPTION
**Pull request by allenahner**
Working example: https://app.bitrise.io/app/c2a3ca92e08085b8/pipelines/97166480-86b3-4fb5-9a0f-e82a35d1bff1

### CODE REVIEW

**Review by jakerobb — APPROVED** [review]
Looks right to me! :)

**Review by jakerobb — COMMENTED** [review]
~Wait, no -- that's not workflow-specific. That will make _all workflows_ run on Linux.~

**Comment by allenahner** [comment]
> Wait, no -- that's not workflow-specific. That will make _all workflows_ run on Linux.

It's under the `android-build` workflow

**Comment by jakerobb** [comment]
Yep, sorry -- ignore me. :)

**Pull request merged**
